apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ${{ secrets.DOCKER_USERNAME }}/task-api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 30008  # NodePort to access externally
      targetPort: 8080  # Inside the container
      nodePort: 30008  # Fixed external port (range: 30000-32767)
  type: NodePort
